// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Link struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Title       string             `json:"title"`
	Url         string             `json:"url"`
	Description pgtype.Text        `json:"description"`
	Domain      pgtype.Text        `json:"domain"`
	FaviconUrl  pgtype.Text        `json:"favicon_url"`
	IsFavorite  pgtype.Bool        `json:"is_favorite"`
	Archived    pgtype.Bool        `json:"archived"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type LinkTag struct {
	LinkID pgtype.UUID `json:"link_id"`
	TagID  pgtype.UUID `json:"tag_id"`
}

type Tag struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         pgtype.Text        `json:"name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
