// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddTagToLink(ctx context.Context, arg AddTagToLinkParams) error
	CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteLink(ctx context.Context, arg DeleteLinkParams) error
	DeleteTag(ctx context.Context, arg DeleteTagParams) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetLinkByID(ctx context.Context, arg GetLinkByIDParams) (Link, error)
	GetTagByID(ctx context.Context, arg GetTagByIDParams) (Tag, error)
	GetTagByName(ctx context.Context, arg GetTagByNameParams) (Tag, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListArchivedLinksByUser(ctx context.Context, arg ListArchivedLinksByUserParams) ([]Link, error)
	ListFavoriteLinksByUser(ctx context.Context, arg ListFavoriteLinksByUserParams) ([]Link, error)
	ListLinksByTag(ctx context.Context, arg ListLinksByTagParams) ([]Link, error)
	ListLinksByUser(ctx context.Context, arg ListLinksByUserParams) ([]Link, error)
	ListTagsByLink(ctx context.Context, linkID pgtype.UUID) ([]Tag, error)
	ListTagsByUser(ctx context.Context, userID pgtype.UUID) ([]Tag, error)
	RemoveTagFromLink(ctx context.Context, arg RemoveTagFromLinkParams) error
	UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error)
	UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
